from __future__ import annotations

from pathlib import Path
import pandas as pd

# Define file paths
LSEG_FILE = Path(r"C:\Users\scelik\Desktop\TRACE3Code\data\raw\LSEG\lseg_active_universe_10y.csv")
MERGED_FILE = Path(
    r"/data/processed/common_companies_by_year_cdp_trucost_factset_lseg_with_trucost_emissions.csv")

def main() -> None:
    """Main execution function to load and inspect the datasets."""
    try:
        """Load the merged Trucost/FactSet/CDP/LSEG dataset and standardize identifiers."""
        if not MERGED_FILE.exists():
            raise FileNotFoundError(f"Merged file not found: {MERGED_FILE}")

        print(f"Loading Merged data from: {MERGED_FILE}")
        merged_df = pd.read_csv(MERGED_FILE, low_memory=False)

        # Ensure cdp_match_score is numeric
        merged_df["cdp_match_score"] = pd.to_numeric(merged_df["cdp_match_score"], errors="coerce")
        merged_df["fuzzy_score"] = pd.to_numeric(merged_df["fuzzy_score"], errors="coerce")

        # Filter for rows where cdp_match_score is strictly below 70
        # (ignoring NaNs which would count as missing data, not low scores)
        filtered_merged_df = merged_df[
            (merged_df["cdp_match_score"] == 1000) &
            (merged_df["fuzzy_score"] == 1000)
            ].copy()

        for year in filtered_merged_df["year"].unique():
            print("year:", year, filtered_merged_df[filtered_merged_df["year"]== year].trucost_isin.count())

        filtered_merged_df.to_csv("data/processed/filtered_cdp_trucost_lseg_factset.csv", index=False)

    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
    except Exception as e:
        print(f"❌ An unexpected error occurred: {e}")


if __name__ == "__main__":
    main()

    # import pandas as pd
    #
    # # 1. Your mapping dictionary (Data Item Name -> dataItemId)
    # di_mapping = {
    #     "Cost Per Rev: Air Pollutants Direct": 319381,
    #     "Cost Per Rev: Air Pollutants Direct & Indirect": 319385,
    #     "Cost Per Rev: Air Pollutants Indirect": 319383,
    #     "Cost Per Rev: Environmental Direct": 319533,
    #     "Cost Per Rev: Environmental Direct & Indirect": 319535,
    #     "Cost Per Rev: Environmental Indirect": 319537,
    #     "Cost Per Rev: GHG Direct": 319438,
    #     "Cost Per Rev: GHG Direct & Indirect": 319442,
    #     "Cost Per Rev: GHG Indirect": 319440,
    #     "Cost Per Rev: Land & Water Poll Direct": 319446,
    #     "Cost Per Rev: Land & Water Poll Direct & Indirect": 319450,
    #     "Cost Per Rev: Land & Water Poll Indirect": 319448,
    #     "Cost Per Rev: Natural Resources Direct": 319466,
    #     "Cost Per Rev: Natural Resources Direct & Indirect": 319470,
    #     "Cost Per Rev: Natural Resources Indirect": 319468,
    #     "Cost Per Rev: Waste Direct": 319546,
    #     "Cost Per Rev: Waste Direct & Indirect": 319554,
    #     "Cost Per Rev: Waste Indirect": 319549,
    #     "Cost Per Rev: Water Direct": 319562,
    #     "Cost Per Rev: Water Direct & Indirect": 319569,
    #     "Cost Per Rev: Water Indirect": 319566,
    #     "Cost: Air Pollutants Direct": 319380,
    #     "Cost: Air Pollutants Direct & Indirect": 319384,
    #     "Cost: Air Pollutants Indirect": 319382,
    #     "Cost: Environmental Direct": 319532,
    #     "Cost: Environmental Direct & Indirect": 319534,
    #     "Cost: Environmental Indirect": 319536,
    #     "Cost: GHG Direct": 319437,
    #     "Cost: GHG Direct & Indirect": 319441,
    #     "Cost: GHG Indirect": 319439,
    #     "Cost: Land & Water Poll Direct": 319445,
    #     "Cost: Land & Water Poll Direct & Indirect": 319449,
    #     "Cost: Land & Water Poll Indirect": 319447,
    #     "Cost: Natural Resources Direct": 319469,
    #     "Cost: Natural Resources Direct & Indirect": 319465,
    #     "Cost: Natural Resources Indirect": 319467,
    #     "Cost: Waste Direct": 319545,
    #     "Cost: Waste Direct & Indirect": 319553,
    #     "Cost: Waste Indirect": 319548,
    #     "Cost: Water Direct": 319560,
    #     "Cost: Water Direct & Indirect": 319568,
    #     "Cost: Water Indirect": 319565,
    #     "GHG Scope 1 Score": 387688,
    #     "GHG Scope 2 Location-based Score": 387689,
    #     "GHG Scope 2 Market-based Score": 387716,
    #     "GHG Scope 3 Downstream Leased Assets Score": 387723,
    #     "GHG Scope 3 Downstream T&D Score": 387719,
    #     "GHG Scope 3 Downstream Total Score": 387718,
    #     "GHG Scope 3 EOL Treatment of Sold Prod Score": 387722,
    #     "GHG Scope 3 Franchises Score": 387724,
    #     "GHG Scope 3 Investments Score": 387725,
    #     "GHG Scope 3 Other Downstream Score": 387726,
    #     "GHG Scope 3 Processing of Sold Products Score": 387720,
    #     "GHG Scope 3 Upstream Score": 387717,
    #     "GHG Scope 3 Use of Sold Products Score": 387721,
    #     "Quant Per Rev: GHG Direct": 319404,
    #     "Quant Per Rev: GHG Direct & Tier 1 Indirect": 319405,
    #     "Quant Per Rev: GHG Scope 1": 319407,
    #     "Quant Per Rev: GHG Scope 2 Location-Based": 319408,
    #     "Quant Per Rev: GHG Scope 2 Market-Based": 368314,
    #     "Quant Per Rev: GHG Scope 3 Cat 10 Proc of Prods": 368740,
    #     "Quant Per Rev: GHG Scope 3 Cat 11 Use of Prods": 368742,
    #     "Quant Per Rev: GHG Scope 3 Cat 12 EoL of Prods": 368741,
    #     "Quant Per Rev: GHG Scope 3 Cat 13 Dwns Lsd Assets": 368754,
    #     "Quant Per Rev: GHG Scope 3 Cat 14 Dwns Franchises": 368755,
    #     "Quant Per Rev: GHG Scope 3 Cat 15 Dwns Investments": 368756,
    #     "Quant Per Rev: GHG Scope 3 Cat 9 Dwns T&D": 368739,
    #     "Quant Per Rev: GHG Scope 3 Downstream Total": 326738,
    #     "Quant Per Rev: GHG Scope 3 Other Downstream": 368757,
    #     "Quant Per Rev: GHG Scope 3 Upstream Total": 319409,
    #     "Quant Per Rev: GHG Tier 1 Indirect": 319406,
    #     "Quant Per Rev: Waste Direct & Indirect": 327790,
    #     "Quant Per Rev: Waste Incineration Direct": 319541,
    #     "Quant Per Rev: Waste Incineration Direct and Indir": 327789,
    #     "Quant Per Rev: Waste Incineration Indirect": 327788,
    #     "Quant Per Rev: Waste Landfill Direct": 319542,
    #     "Quant Per Rev: Waste Landfill Direct and Indirect": 327787,
    #     "Quant Per Rev: Waste Landfill Indirect": 327786,
    #     "Quant Per Rev: Waste Radioactive HLW Direct": 319543,
    #     "Quant Per Rev: Waste Recycled Direct": 319544,
    #     "Quant Per Rev: Water Direct & Indirect Consump Sum": 326719,
    #     "Quant Per Rev: Water Direct and Purch Consumption": 319558,
    #     "Quant Per Rev: Water Direct Consumption Cooling": 319556,
    #     "Quant Per Rev: Water Direct Consumption Process": 319557,
    #     "Quant Per Rev: Water Indirect Consumption Cooling": 326717,
    #     "Quant Per Rev: Water Indirect Consumption Process": 326718,
    #     "Quant Per Rev: Water Purchased Consumption": 319559,
    #     "Quantity: GHG Direct": 319410,
    #     "Quantity: GHG Direct & Tier 1 Indirect": 319411,
    #     "Quantity: GHG Scope 1": 319413,
    #     "Quantity: GHG Scope 1 As Reported": 376883,
    #     "Quantity: GHG Scope 2 Location-Based": 319414,
    #     "Quantity: GHG Scope 2 Location-Based As Reported": 376884,
    #     "Quantity: GHG Scope 2 Market-Based": 367750,
    #     "Quantity: GHG Scope 2 Market-Based As Reported": 376886,
    #     "Quantity: GHG Scope 3 Cat 1 Ups Purch Goods As Reported": 378459,
    #     "Quantity: GHG Scope 3 Cat 10 Dwns Proc of Prods": 368653,
    #     "Quantity: GHG Scope 3 Cat 10 Dwns Proc of Prods As Reported": 377767,
    #     "Quantity: GHG Scope 3 Cat 11 Dwns Use of Prods": 368654,
    #     "Quantity: GHG Scope 3 Cat 11 Dwns Use of Prods As Reported": 377768,
    #     "Quantity: GHG Scope 3 Cat 12 Dwns EoL of Prods": 368655,
    #     "Quantity: GHG Scope 3 Cat 12 Dwns EoL of Prods As Reported": 377405,
    #     "Quantity: GHG Scope 3 Cat 13 Dwns Leased Assets": 368704,
    #     "Quantity: GHG Scope 3 Cat 13 Dwns Leased Assets As Reported": 377406,
    #     "Quantity: GHG Scope 3 Cat 14 Dwns Franchises": 368705,
    #     "Quantity: GHG Scope 3 Cat 14 Dwns Franchises As Reported": 377407,
    #     "Quantity: GHG Scope 3 Cat 15 Dwns Investments": 368706,
    #     "Quantity: GHG Scope 3 Cat 15 Dwns Investments As Reported": 377408,
    #     "Quantity: GHG Scope 3 Cat 2 Ups Capital Goods As Reported": 378680,
    #     "Quantity: GHG Scope 3 Cat 3 Ups Fuel or Energy As Reported": 378681,
    #     "Quantity: GHG Scope 3 Cat 4 & 6 Ups T&D & Trv As Reported": 378682,
    #     "Quantity: GHG Scope 3 Cat 5 Ups Waste Generated As Reported": 378683,
    #     "Quantity: GHG Scope 3 Cat 7 Ups Emp Commuting As Reported": 378684,
    #     "Quantity: GHG Scope 3 Cat 8 Ups Leased Assets As Reported": 378685,
    #     "Quantity: GHG Scope 3 Cat 9 Dwns T&D": 368652,
    #     "Quantity: GHG Scope 3 Cat 9 Dwns T&D As Reported": 377766,
    #     "Quantity: GHG Scope 3 Downstream Total": 326737,
    #     "Quantity: GHG Scope 3 Other Downstream": 368707,
    #     "Quantity: GHG Scope 3 Other Downstream As Reported": 377409,
    #     "Quantity: GHG Scope 3 Other Upstream As Reported": 378686,
    #     "Quantity: GHG Scope 3 Upstream Total": 319415,
    #     "Quantity: GHG Tier 1 Indirect": 319412,
    #     "Quantity: Waste Direct & Indirect": 327795,
    #     "Quantity: Waste Incineration Direct": 319547,
    #     "Quantity: Waste Incineration Direct and Indirect": 327794,
    #     "Quantity: Waste Incineration Indirect": 327793,
    #     "Quantity: Waste Landfill Direct": 319550,
    #     "Quantity: Waste Landfill Direct and Indirect": 327792,
    #     "Quantity: Waste Landfill Indirect": 327791,
    #     "Quantity: Waste Mining Overburden Direct": 327797,
    #     "Quantity: Waste Mining Tailings Direct": 327796,
    #     "Quantity: Waste Radioactive HLW Direct": 319551,
    #     "Quantity: Waste Recycled Direct": 319552,
    #     "Quantity: Water Direct & Indirect Consumption Sum": 326714,
    #     "Quantity: Water Direct and Purchased Consumption": 319564,
    #     "Quantity: Water Direct Consumption Cooling": 319561,
    #     "Quantity: Water Direct Consumption Process": 319563,
    #     "Quantity: Water Direct Consumption Process As Reported": 377790,
    #     "Quantity: Water Indirect Consumption Cooling": 326709,
    #     "Quantity: Water Indirect Consumption Process": 326710,
    #     "Quantity: Water Purchased Consumption": 319567,
    #     "Trucost Total Revenue": 319522,
    #     "Weighted Contribution: Environmental Disclosure": 329704,
    #     "Weighted Contribution: GHG Disclosure": 319416,
    #     "Weighted Contribution: Land & Water Poll Discl": 326726,
    #     "Weighted Contribution: Waste Disclosure": 319555,
    #     "Weighted Contribution: Water Disclosure": 319570,
    #     "Effective Date of Environmental Cost Calculation": 323615,
    #     "Effective Date of Revenue Calculation": 323618,
    #     "GHG Scope 3 Downstream Calculation As Of": 329688,
    #     "Research Type": 376014,
    #     "Source: GHG Scope 1": 319403,
    #     "Source: GHG Scope 1 As Reported": 377148,
    #     "Source: GHG Scope 2 Location-Based": 329689,
    #     "Source: GHG Scope 2 Location-Based As Reported": 377149,
    #     "Source: GHG Scope 2 Market-Based": 368702,
    #     "Source: GHG Scope 2 Market-Based As Reported": 377758,
    #     "Source: GHG Scope 3 Air Transportation": 329692,
    #     "Source: GHG Scope 3 Cat 1 Ups Purch Goods As Reported": 379572,
    #     "Source: GHG Scope 3 Cat 10 Dwns Proc of Prods": 368735,
    #     "Source: GHG Scope 3 Cat 10 Dwns Proc of Prods As Reported": 377760,
    #     "Source: GHG Scope 3 Cat 11 Dwns Use of Prods": 368736,
    #     "Source: GHG Scope 3 Cat 11 Dwns Use of Prods As Reported": 377852,
    #     "Source: GHG Scope 3 Cat 12 Dwns EoL of Prods": 368737,
    #     "Source: GHG Scope 3 Cat 12 Dwns EoL of Prods As Reported": 377850,
    #     "Source: GHG Scope 3 Cat 13 Dwns Leased Assets": 368746,
    #     "Source: GHG Scope 3 Cat 13 Dwns Leased Assets As Reported": 377849,
    #     "Source: GHG Scope 3 Cat 14 Dwns Franchises": 368747,
    #     "Source: GHG Scope 3 Cat 14 Dwns Franchises As Reported": 377851,
    #     "Source: GHG Scope 3 Cat 15 Dwns Investments": 368748,
    #     "Source: GHG Scope 3 Cat 15 Dwns Investments As Reported": 377764,
    #     "Source: GHG Scope 3 Cat 2 Ups Capital Goods As Reported": 379721,
    #     "Source: GHG Scope 3 Cat 3 Ups Fuel or Energy As Reported": 379722,
    #     "Source: GHG Scope 3 Cat 4 & 6 Ups T&D & Trv As Reported": 379723,
    #     "Source: GHG Scope 3 Cat 5 Ups Waste Generated As Reported": 379724,
    #     "Source: GHG Scope 3 Cat 7 Ups Emp Commuting As Reported": 379725,
    #     "Source: GHG Scope 3 Cat 8 Ups Leased Assets As Reported": 379726,
    #     "Source: GHG Scope 3 Cat 9 Dwns T&D": 368730,
    #     "Source: GHG Scope 3 Cat 9 Dwns T&D As Reported": 377759,
    #     "Source: GHG Scope 3 Downstream Total": 326730,
    #     "Source: GHG Scope 3 Other Downstream": 368749,
    #     "Source: GHG Scope 3 Other Downstream As Reported": 377765,
    #     "Source: GHG Scope 3 Other Upstream As Reported": 379727,
    #     "Source: GHG Scope 3 Rail Transportation": 329693,
    #     "Source: GHG Scope 3 Truck Transportation": 329694,
    #     "Source: GHG Scope 3 Upstream Total": 368758,
    #     "Source: Waste Incinerate Direct Hazardous": 329699,
    #     "Source: Waste Incinerate Direct Non-Hazardous": 329700,
    #     "Source: Waste Landfill Direct Hazardous": 329697,
    #     "Source: Waste Landfill Direct Non-Hazardous": 329698,
    #     "Source: Waste Radioactive HLW Direct": 329701,
    #     "Source: Waste Recycled Direct Hazardous": 329702,
    #     "Source: Waste Recycled Direct Non-Hazardous": 329703,
    #     "Source: Water Direct Consumption Cooling": 326727,
    #     "Source: Water Direct Consumption Process": 326729,
    #     "Source: Water Direct Consumption Process As Reported": 377763,
    #     "Source: Water Purchased Consumption": 326728,
    #     "Bitumns and Lignit Surface Coal Mng Rev/ Total Rev": 319388,
    #     "Bitumns Undergrnd Coal Mining Rev/ Total Revenue": 319390,
    #     "Coal Extraction: Deep Mined": 319417,
    #     "Coal Extraction: Open Cast": 319418,
    #     "Coal Extraction: Undefined": 319419,
    #     "Coal Mining Rev: Bituminous and Lignite Surface": 319389,
    #     "Coal Mining Rev: Bituminous Coal Undergrnd Mining": 319391,
    #     "Coal Mining Revenue": 319531,
    #     "Coal Mining Revenue/ Total Revenue": 319530,
    #     "Coal Power Generation Revenue/ Total Revenue": 319433,
    #     "Coal Power Generation/ Total Power Generation": 319428,
    #     "Comp Power Generation: Liquid Petroleum Gas (LPG)": 319457,
    #     "Company CapEx: Coal Exploration": 319392,
    #     "Company CapEx: Gas Exploration": 319394,
    #     "Company CapEx: Oil and Gas Exploration": 319396,
    #     "Company CapEx: Oil Exploration": 319398,
    #     "Company CapEx: Undefined Fossil Fuel Exploration": 319400,
    #     "Company CO2 Emissions: All Fossil Fuel Reserves": 319526,
    #     "Company CO2 Emissions: Coal Reserves": 319514,
    #     "Company CO2 Emissions: Gas Reserves": 319516,
    #     "Company CO2 Emissions: Oil and Gas Reserves": 319520,
    #     "Company CO2 Emissions: Oil Reserves": 319518,
    #     "Company GHG Emissions: All Fossil Fuel Power Generation": 319524,
    #     "Company GHG Emissions: Coal Power Generation": 319431,
    #     "Company GHG Emissions: Liquid Natural Gas (LNG) Power Generation": 319455,
    #     "Company GHG Emissions: Liquid Petroleum Gas (LPG) Power Generation": 319459,
    #     "Company GHG Emissions: Natural Gas Power Generation": 319463,
    #     "Company GHG Emissions: Petroleum (Oil) Power Generation": 319477,
    #     "Company Power Generation: Biomass": 319386,
    #     "Company Power Generation: Coal": 319429,
    #     "Company Power Generation: Geothermal": 319435,
    #     "Company Power Generation: Hydroelectric": 319443,
    #     "Company Power Generation: Landfill Gas": 319451,
    #     "Company Power Generation: Liquid Natural Gas (LNG)": 319453,
    #     "Company Power Generation: Natural Gas": 319461,
    #     "Company Power Generation: Nuclear": 319471,
    #     "Company Power Generation: Petroleum (Oil)": 319475,
    #     "Company Power Generation: Solar": 319528,
    #     "Company Power Generation: Undefined Sources": 319473,
    #     "Company Power Generation: Wave and Tidal": 319571,
    #     "Company Power Generation: Wind": 319573,
    #     "Company Probable Reserves: Conventional Oil": 319498,
    #     "Company Probable Reserves: Metallurgical Coal": 319500,
    #     "Company Probable Reserves: Natural Gas": 319502,
    #     "Company Probable Reserves: Oil and Gas": 319504,
    #     "Company Probable Reserves: Other Coal": 319506,
    #     "Company Probable Reserves: Shale Gas": 319508,
    #     "Company Probable Reserves: Thermal Coal": 319510,
    #     "Company Probable Reserves: Unconventional Oil": 319512,
    #     "Company Proven Reserves: Conventional Oil": 319482,
    #     "Company Proven Reserves: Metallurgical Coal": 319484,
    #     "Company Proven Reserves: Natural Gas": 319486,
    #     "Company Proven Reserves: Oil and Gas": 319488,
    #     "Company Proven Reserves: Other Coal": 319490,
    #     "Company Proven Reserves: Shale Gas": 319492,
    #     "Company Proven Reserves: Thermal Coal": 319494,
    #     "Company Proven Reserves: Unconventional Oil": 319496,
    #     "Metallurgical Coal Mining Revenue": 323610,
    #     "Metallurgical Coal Mining Revenue/ Total Revenue": 323609,
    #     "Revenue: Coal Power Generation": 319434,
    #     "Thermal Coal Mining Revenue": 323614,
    #     "Thermal Coal Mining Revenue/ Total Revenue": 323613,
    #     "Undefined Coal Mining Revenue": 323612,
    #     "Undefined Coal Mining Revenue/ Total Revenue": 323611,
    #     "Coal Gasification": 323619,
    #     "Coal Liquefaction": 323620,
    #     "Coal Mining Data Source": 319427,
    #     "Coal Mining Methodology": 319425,
    #     "Company Power Generation Data Source": 319480,
    #     "Company Reserves Data Source": 319580,
    #     "Effective Date of Coal Mining Calculation": 323617,
    #     "Effective Date of Fossil Fuel and Energy Calculation": 323616,
    #     "Company Sector CO2 Emissions: All Fossil Fuel Reserves": 319527,
    #     "Company Sector CO2 Emissions: Coal Reserves": 319515,
    #     "Company Sector CO2 Emissions: Gas Reserves": 319517,
    #     "Company Sector CO2 Emissions: Oil and Gas Reserves": 319521,
    #     "Company Sector CO2 Emissions: Oil Reserves": 319519,
    #     "Company Sector GHG Emissions: All Fossil Fuel Power Generation": 319525,
    #     "Company Sector GHG Emissions: Coal Power Generation": 319432,
    #     "Company Sector GHG Emissions: Liquid Natural Gas (LNG) Power Generation": 319456,
    #     "Company Sector GHG Emissions: Liquid Petroleum Gas (LPG) Power Generation": 319460,
    #     "Company Sector GHG Emissions: Natural Gas Power Generation": 319464,
    #     "Company Sector GHG Emissions: Petroleum (Oil) Power Generation": 319478,
    #     "Company Sector Power Generation: Biomass": 319387,
    #     "Company Sector Power Generation: Coal": 319430,
    #     "Company Sector Power Generation: Geothermal": 319436,
    #     "Company Sector Power Generation: Hydroelectric": 319444,
    #     "Company Sector Power Generation: Landfill Gas": 319452,
    #     "Company Sector Power Generation: Liquid Natural Gas (LNG)": 319454,
    #     "Company Sector Power Generation: Liquid Petroleum Gas (LPG)": 319458,
    #     "Company Sector Power Generation: Natural Gas": 319462,
    #     "Company Sector Power Generation: Nuclear": 319472,
    #     "Company Sector Power Generation: Petroleum (Oil)": 319476,
    #     "Company Sector Power Generation: Solar": 319529,
    #     "Company Sector Power Generation: Undefined Sources": 319474,
    #     "Company Sector Power Generation: Wave and Tidal": 319572,
    #     "Company Sector Power Generation: Wind": 319574,
    #     "Company Sector Probable Reserves: Conventional Oil": 319499,
    #     "Company Sector Probable Reserves: Metallurgical Coal": 319501,
    #     "Company Sector Probable Reserves: Natural Gas": 319503,
    #     "Company Sector Probable Reserves: Oil and Gas": 319505,
    #     "Company Sector Probable Reserves: Other Coal": 319507,
    #     "Company Sector Probable Reserves: Shale Gas": 319509,
    #     "Company Sector Probable Reserves: Thermal Coal": 319511,
    #     "Company Sector Probable Reserves: Unconventional Oil": 319513,
    #     "Company Sector Proven Reserves: Conventional Oil": 319483,
    #     "Company Sector Proven Reserves: Metallurgical Coal": 319485,
    #     "Company Sector Proven Reserves: Natural Gas": 319487,
    #     "Company Sector Proven Reserves: Oil and Gas": 319489,
    #     "Company Sector Proven Reserves: Other Coal": 319491,
    #     "Company Sector Proven Reserves: Shale Gas": 319493,
    #     "Company Sector Proven Reserves: Thermal Coal": 319495,
    #     "Company Sector Proven Reserves: Unconventional Oil": 319497,
    #     "Company Sector Power Generation Data Source": 319858,
    #     "Company Sector Reserves Data Source": 319582,
    #     "Company Sector Revenue": 319523,
    #     "Percent of Total Company Revenue (%)": 319540,
    #     "Effective Date of Sector Revenue Calculation": 324389,
    # }
    #
    # # 2. Invert the dictionary to map: "319381" -> "Cost Per Rev: Air Pollutants Direct"
    # id_to_name = {str(v): k for k, v in di_mapping.items()}
    #
    # # 3. Create the rename mapping for the exact DataFrame columns
    # # It will look for columns named "di_319381_text" and extract "319381" to look it up
    # rename_dict = {}
    # for col in filtered_merged_df.columns:
    #     if col.startswith("di_") and col.endswith("_text"):
    #         # Extract the numeric ID part between 'di_' and '_text'
    #         col_id = col[3:-5]
    #         if col_id in id_to_name:
    #             rename_dict[col] = id_to_name[col_id]
    #
    # # 4. Apply the renaming
    # filtered_merged_df.rename(columns=rename_dict, inplace=True)

    # # 5. Drop any remaining "di_..._text" columns that weren't in the mapping
    # cols_to_drop = [c for c in filtered_merged_df.columns if c.startswith("di_") and c.endswith("_text")]
    # filtered_merged_df.drop(columns=cols_to_drop, inplace=True)
    #
    # print(f"✅ Renamed {len(rename_dict)} columns.")
    # print(f"✅ Dropped {len(cols_to_drop)} unmapped 'di_' columns.")
    # print(f"New shape: {filtered_merged_df.shape}")