from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2] / "reports" / "MDP"
original = (ROOT / 'climate_policy_timeline_2016_2025.tex').read_text(encoding='utf-8')
refs = {}
for line in original.splitlines():
    m = re.fullmatch(r'\\source\{([^}]+)\}\{([^}]+)\}\{([^}]+)\}\{([^}]+)\}', line)
    if m:
        key, author, title, url = m.groups()
        refs[key] = (author, title, url)

refs.update({
'nlclimate': ('Government of the Netherlands (2023)', 'Klimaatwet: version effective 22 July 2023', 'https://wetten.overheid.nl/BWBR0042394/2023-07-22/'),
'nlsde': ('Netherlands Enterprise Agency', 'SDE++: Facts and figures', 'https://www.rvo.nl/subsidies-financiering/sde/aanvragen/feiten-en-cijfers'),
'nlsdescope': ('Netherlands Enterprise Agency', 'Stimulation of Sustainable Energy Production and Climate Transition', 'https://english.rvo.nl/subsidies-financiering/sde'),
'nleia': ('Dutch Tax Administration (2025)', 'Energie-investeringsaftrek 2025', 'https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/winst/inkomstenbelasting/verandering_inkomstenbelasting_vorige_jaren/veranderingen-inkomstenbelasting-2025/investeringsaftrek-2025/energie-investeringsaftrek-2025'),
'nlmia': ('Netherlands Enterprise Agency (2025)', 'MIA and Vamil tax scheme', 'https://english.rvo.nl/subsidies-financing/mia-vamil/mia-and-vamil-tax-scheme'),
'nlenergy': ('Netherlands Enterprise Agency (2023)', 'Information on the energy-saving obligation and reporting obligations', 'https://www.rvo.nl/onderwerpen/energiebesparingsplicht-2023/voorlichtingsmateriaal'),
'nlenergydate': ('Netherlands Enterprise Agency', 'About the energy-saving obligation', 'https://www.rvo.nl/onderwerpen/energiebesparingsplicht/over-de-energiebesparingplicht'),
'nlze': ('Netherlands Enterprise Agency / Business.gov.nl', 'Zero-emission zones in the Netherlands', 'https://business.gov.nl/sustainable-business/sustainable-business-operations/zero-emission-zones-in-the-netherlands/'),
'nlze2025': ('Government of the Netherlands (2024)', 'Road Traffic Signs and Regulations in the Netherlands: Article 86e', 'https://www.government.nl/site/binaries/site-content/collections/documents/2024/02/09/road-traffic-signs-and-regulations-in-the-netherlands/Road%2BTraffic%2BSigns%2Band%2BRegulations%2Bin%2Bthe%2BNetherlands.pdf'),
'nlaanzet': ('Netherlands Enterprise Agency', 'Aanschafsubsidie Zero-Emissie Trucks (AanZET)', 'https://www.rvo.nl/subsidies-financiering/aanzet'),
'nlaanzetstart': ('Netherlands Enterprise Agency (2023)', 'Economic significance of the Dutch electric transport sector 2020-2022', 'https://www.rvo.nl/sites/default/files/2023-11/RVO%20-%20Rapport%20Economische%20betekenis%20sector%20EV%20Nederland%202020-2022.pdf'),
'nlseba': ('Netherlands Enterprise Agency', 'Subsidieregeling Emissieloze Bedrijfsautos (SEBA)', 'https://www.rvo.nl/subsidies-financiering/seba'),
'swedentax': ('Government Offices of Sweden', "Sweden's carbon tax", 'https://www.government.se/government-policy/taxes-and-tariffs/swedens-carbon-tax/'),
'francetax': ('Ministry for Ecological Transition, France', 'Fiscalite carbone', 'https://www.ecologie.gouv.fr/politiques-publiques/fiscalite-carbone'),
'irelandtax': ('Houses of the Oireachtas (2025)', 'Tax Code: Parliamentary Question 346, 22 January 2025', 'https://www.oireachtas.ie/en/debates/question/2025-01-22/346/'),
'irelandstart': ('Revenue Commissioners, Ireland', 'Natural Gas Carbon Tax', 'https://www.revenue.ie/en/companies-and-charities/excise-and-licences/energy-taxes/natural-gas-carbon-tax/index.aspx'),
'nltax': ('Government of the Netherlands', 'CO2-heffing voor industrie', 'https://www.rijksoverheid.nl/onderwerpen/klimaatverandering/co2-heffing-voor-industrie'),
'nltaxets': ('Dutch Emissions Authority (2022)', 'NEa allocates industrial carbon-levy dispensation rights', 'https://www.emissieautoriteit.nl/actueel/nieuws/2022/04/28/nea-stort-dispensatierechten-voor-co2-heffing-industrie'),
'denmarktax': ('Ministry of Climate, Energy and Utilities, Denmark (2025)', 'Klimaprogram 2025', 'https://www.kefm.dk/Media/638948087473597195/Klimaprogram%202025.pdf'),
'germanyprice': ('German Environment Agency', 'Der Nationale Emissionshandel', 'https://www.umweltbundesamt.de/der-nationale-emissionshandel'),
'germanystart': ('German Environment Agency (2020)', 'CO2 pricing for emissions in heating and transport sectors to start in new year in Germany', 'https://www.umweltbundesamt.de/en/press/pressinformation/co2-pricing-for-emissions-in-heating-transport'),
'powerrepeal': ('US Environmental Protection Agency (2025)', 'EPA Proposes Repeal of Regulations for Power Plants', 'https://www.epa.gov/newsreleases/epa-proposes-repeal-biden-harris-epa-regulations-power-plants-which-if-finalized-would'),
'eed': ('Council of the European Union (2023)', 'Council adopts energy efficiency directive', 'https://www.consilium.europa.eu/en/press/press-releases/2023/07/25/council-adopts-energy-efficiency-directive/'),
'esr': ('Council of the European Union (2023)', 'Fit for 55 package: Council adopts regulations on effort sharing and land use and forestry sector', 'https://www.consilium.europa.eu/en/press/press-releases/2023/03/28/fit-for-55-package-council-adopts-regulations-on-effort-sharing-and-land-use-and-forestry-sector/'),
'cars': ('Council of the European Union (2023)', 'Fit for 55: Council adopts regulation on CO2 emissions for new cars and vans', 'https://www.consilium.europa.eu/en/press/press-releases/2023/03/28/fit-for-55-council-adopts-regulation-on-co2-emissions-for-new-cars-and-vans/'),
'sb32': ('California Air Resources Board', 'GHG 1990 Emissions Level and 2020 Limit', 'https://ww2.arb.ca.gov/ghg-2020-limit'),
'koreatarget': ('Ministry of Environment, Republic of Korea (2022)', 'Legislating the carbon-neutrality vision and greenhouse-gas reduction commitment [Korean]', 'https://me.go.kr/home/web/board/read.do?boardId=1515170&boardMasterId=1'),
'ghgp': ('GHG Protocol', 'Calculation Tools FAQ', 'https://ghgprotocol.org/calculation-tools-faq'),
'methanedelay': ('US Environmental Protection Agency (2025)', '2025 Interim Final Rule to Extend Compliance Deadlines', 'https://www.epa.gov/controlling-air-pollution-oil-and-natural-gas-operations/2025-interim-final-rule-extend-compliance'),
'omnibus': ('Council of the European Union (2025)', 'Council and Parliament strike a deal to simplify sustainability reporting and due diligence requirements and boost EU competitiveness', 'https://www.consilium.europa.eu/en/press/press-releases/2025/12/09/council-and-parliament-strike-a-deal-to-simplify-sustainability-reporting-and-due-diligence-requirements-and-boost-eu-competitiveness/'),
'gxdates': ('Agency for Natural Resources and Energy, Japan (2025)', 'GX Policy: Achieving Decarbonization and Economic Growth Together', 'https://www.enecho.meti.go.jp/en/category/special/article/detail_214.html'),
'sgscope': ('Ministry of Sustainability and the Environment, Singapore', 'Climate Game Changer', 'https://www.mse.gov.sg/policies/climate-change/climate-game-changer/'),
'twscope': ('Ministry of Environment, Taiwan (2023)', 'Power Generators and Large Manufacturers Targeted for Carbon Fee Collection for Now', 'https://www.moenv.gov.tw/en/news/press-releases/12023.html'),
})

# Columns: region | instrument/type | purpose/target | affected firms | dates | inferred Scope 3 link | reference keys
DATA = '''Global|Paris Agreement [R: treaty]|Coordinate national mitigation commitments and reporting; pursue temperature goals.|Governments directly; firms indirectly through national implementation.|Entered into force 4 Nov 2016; national policies have separate schedules.|Context for supplier-country climate risk and long-term procurement; no direct corporate Scope 3 mandate.|paris
European Union|Non-financial reporting guidance [I]|Help companies disclose environmental and other non-financial information under the existing NFRD.|Large public-interest entities covered by NFRD; suppliers indirectly through information requests.|Guidance issued Jun 2017; climate supplement Jun 2019; non-binding guidance.|Encourages value-chain information requests and more consistent supplier disclosures.|nfrdguidance
European Union|Renewable Energy Directive: RED II / RED III [R]|Raise renewable energy's share: 32% target in 2018; binding 42.5% EU target by 2030 in 2023, with 45% indicative ambition.|Member states directly; energy producers, fuel suppliers and industrial users through implementing rules.|RED II adopted 2018; RED III adopted 2023; national implementation phased; target year 2030.|Cleaner supplier energy can reduce purchased-product footprints; supports supplier renewable-energy engagement.|eu2018,red3
European Union|Energy Efficiency Directive [R]|Reduce energy demand; revised target is 11.7% lower final energy use in 2030 than the 2020 forecast for 2030.|Member states; businesses subject to energy-management/audit requirements through national rules.|Revised 2018 and 2023; phased national implementation; target year 2030.|Supplier efficiency may lower embodied emissions and costs; supports procurement of efficient products.|eu2018,eed
European Union|Energy Union Governance Regulation [R]|Coordinate national energy and climate plans and monitor progress.|Member states directly; energy and industrial firms indirectly.|Adopted 2018; plans cover 2021-2030 with updates and reporting.|Provides country-level policy assumptions for supplier location and investment scenarios.|eu2018
European Union|European Green Deal [I]|Set the overarching direction toward climate neutrality by 2050.|Firms across sectors indirectly; specific obligations arise from subsequent laws.|Launched Dec 2019; no single company compliance date.|Signals future demand for low-carbon materials, circular products and logistics.|greendeal
European Union|Taxonomy Regulation [R]|Classify environmentally sustainable activities and improve investment transparency.|In-scope reporting companies and financial-market participants; project developers seeking finance.|Entered into force Jul 2020; climate-related application from 2022, with phased disclosures.|May influence financing of supplier upgrades and low-carbon capital goods; no general Scope 3 cap.|taxonomy
European Union|European Climate Law [R]|At least 55% lower EU net GHG emissions by 2030 versus 1990; climate neutrality by 2050.|EU institutions and member states directly; firms through implementing policies.|Entered into force 2021; milestones 2030 and 2050.|Provides a policy scenario for supplier engagement and investment; not a 55% mandate for each firm.|climatelaw
European Union|Recovery and Resilience Facility [R: funding]|Finance recovery reforms and investment; at least 37% of national plan allocations support climate objectives.|Eligible project developers, contractors, technology providers and other beneficiaries under national plans.|Established 2021; national projects and milestones implemented through 2026.|Funding may enable supplier retrofits, cleaner transport and low-carbon equipment purchases.|rrf
European Union|CSRD [R]|Require standardized sustainability reporting and assurance.|Covered large/public-interest firms and other phased categories, including qualifying non-EU groups; suppliers indirectly.|Adopted 2022; first wave reports in 2025 on FY2024; later waves delayed in 2025.|Direct driver of value-chain emissions data collection where material, supplier engagement and target tracking.|csrd,stopclock
European Union|REPowerEU [I]|Accelerate energy savings, renewables and diversification away from Russian fossil fuels.|Energy developers, industrial energy users and beneficiaries of national support programmes.|Launched May 2022; implementation through national plans and later measures.|Supports supplier fuel switching and renewables; changes energy-security and sourcing assumptions.|repower
European Union|EU ETS reform and maritime extension [R]|Tighten the carbon cap: 62% reduction in covered emissions by 2030 versus 2005; extend coverage.|Covered power/industrial installations, aircraft operators and shipping companies; buyers through costs.|Reform adopted 2023; shipping included from 2024, with surrender shares of 40%, 70%, 100% for 2024, 2025, 2026 emissions.|Changes prices of carbon-intensive inputs and freight; encourages low-carbon suppliers and carriers.|fit55
European Union|CBAM [R]|Address carbon leakage by aligning the carbon cost of selected imports with EU production.|EU importers of covered cement, iron/steel, aluminium, fertilizers, electricity and hydrogen; non-EU producers supply data.|Reporting began 1 Oct 2023; transitional phase through 2025; financial regime scheduled from 2026.|Prompts supplier-specific embedded-emissions data and sourcing comparisons; CBAM boundaries differ from a full Scope 3 inventory.|cbam
European Union|ESRS, especially E1 [R]|Specify sustainability disclosures, including material Scope 1, 2 and 3 emissions, targets and transition information.|Companies reporting under CSRD, subject to materiality and phase-ins.|Adopted 2023; first application to FY2024, reported in 2025; later cohorts follow CSRD schedules.|Direct accounting link: define material value-chain emissions, improve supplier data and disclose progress.|esrs
European Union|CSDDD [R]|Require due diligence on adverse human-rights/environmental impacts; climate-transition planning in the 2024 text.|Large EU firms and qualifying non-EU firms under statutory thresholds; business partners indirectly.|Adopted 2024; no company application in 2016-2025; first phase shifted to 2028 by Apr 2025 law; Dec 2025 reform deal remained provisional.|May support supplier screening and engagement; not a blanket mandate to cut every supplier's GHG emissions.|csddd,stopclock,omnibus
European Union|Net-Zero Industry Act [R]|Scale clean-technology manufacturing; streamline permitting and apply relevant procurement provisions.|Net-zero technology manufacturers, project developers and public purchasers.|Adopted 2024; implementation phased after entry into force.|Can improve availability of low-carbon capital goods and alter technology/supplier selection.|nzia
European Union|Stop-the-clock directive [R]|Postpone specified CSRD and CSDDD implementation dates.|CSRD second/third waves and firms in the first CSDDD application phase.|Adopted Apr 2025: two-year CSRD delay; one-year CSDDD transposition/first-phase delay.|Changes the timing of mandatory supplier-data and due-diligence programmes; not an emissions target.|stopclock
European Union|Clean Industrial Deal and CISAF [I; state-aid framework]|Support clean energy, industrial decarbonization and clean-technology production.|Eligible industrial firms, clean-tech manufacturers and energy projects receiving national support.|Deal launched Feb 2025; state-aid framework adopted Jun 2025; individual schemes have separate dates.|May improve economics of supplier decarbonization, low-carbon materials and long-term purchasing contracts.|cleandeal
European Union|Effort Sharing Regulation [R]|Binding national targets for covered sectors: collective 40% cut by 2030 versus 2005 after the 2023 revision.|Member states directly; transport, buildings, agriculture, waste and small industry through national measures.|Adopted 2018; strengthened 2023; annual allocations for 2021-2030.|Influences freight, agricultural sourcing and waste-service emissions via national measures.|esr
European Union|CO2 standards for new cars and vans [R]|New-car fleet target 55% lower and new-van target 50% lower from 2030, relative to 2021 targets.|Manufacturers of new cars/vans; fleet buyers and leasing/logistics firms indirectly.|Revised 2023; these targets apply 2030-2034.|Influences outsourced transport and vehicle choice; affects use-of-sold-products emissions for manufacturers.|cars
United States|Phase 2 heavy-duty vehicle standards [R]|Reduce fuel consumption and GHG emissions from new trucks and engines.|Heavy-duty vehicle/engine manufacturers; freight operators indirectly.|Adopted 2016; main truck/engine standards phased through model years 2021, 2024 and 2027.|Cleaner carrier fleets may reduce purchased freight emissions; supports carrier-selection criteria.|usphase2
United States|California SB 32 [R]|Reduce statewide GHG emissions at least 40% below 1990 by 2030.|California state agencies directly; firms through implementing measures.|Enacted 2016; target year 2030.|Shapes supplier investment, California sourcing and logistics scenarios; not a uniform firm-level target.|sb32
United States|California AB 398 / cap-and-trade extension [R]|Extend the existing emissions-trading framework through 2030.|Covered industrial emitters, electricity suppliers/importers and fuel suppliers.|Enacted 2017; extended framework governs the post-2020 period through 2030 as adopted.|Carbon costs can pass into purchased inputs and freight, changing procurement economics.|california
United States|Section 45Q expansion [R: tax incentive]|Make eligible carbon capture, utilization and storage investments more attractive.|Eligible capture project owners and partners, including industrial and energy facilities.|Expanded 2018; enhanced again by IRA in 2022; eligibility depends on project/tax rules.|May lower actual supplier product footprints where capture is attributable and verified; credits alone do not establish Scope 3 reductions.|us45q,ira
United States|AIM Act [R]|Phase down HFC production/consumption 85% by 2036 versus statutory baselines.|HFC producers/importers and affected refrigeration, air-conditioning and equipment businesses.|Enacted Dec 2020; allowance phasedown began 2022; sector restrictions phased.|Supports lower-GWP equipment and cold-chain procurement; effects depend on leakage and inventory boundaries.|aim
United States|Bipartisan Infrastructure Law [R: funding]|Fund clean-energy infrastructure and demonstrations, including more than USD 62 billion for DOE.|Eligible utilities, manufacturers, developers, transport projects and infrastructure contractors.|Enacted Nov 2021; awards and deployment occur over multiple programme-specific years.|May enable lower-carbon freight infrastructure and supplier technology adoption.|bil
United States|Inflation Reduction Act [R: incentives]|Support clean electricity, manufacturing, hydrogen, vehicles, efficiency and carbon capture.|Eligible project developers, manufacturers, commercial buyers and other tax-credit recipients.|Enacted Aug 2022; provisions phased from 2022/2023 onward; some incentives changed in 2025.|Can lower costs of supplier abatement and low-carbon inputs; sourcing conditions can influence supplier location.|ira,ev2025
United States|Oil and gas methane standards [R]|Reduce methane through equipment standards, monitoring and leak controls.|Covered oil/gas operators; states implement guidelines for existing sources.|Finalized Dec 2023, published Mar 2024; phased compliance; several deadlines extended in 2025.|May reduce upstream emissions of purchased fuels; supports verified low-methane fuel sourcing.|methane2023,methanedelay
United States|Power-plant CO2 standards [R]|Limit emissions from covered existing coal and new gas generating units.|Covered power generators; states implement existing-source plans.|Finalized Apr 2024; unit-specific requirements extend into the 2030s; repeal proposed in 2025.|Supplier grid decarbonization may lower embodied product emissions; a buyer's own purchased electricity is generally Scope 2.|power2024,powerrepeal
United States|2025 clean-vehicle credit termination [R]|End specified federal clean-vehicle tax incentives under the 2025 tax law.|New/used vehicle buyers, commercial fleet purchasers, manufacturers and dealers.|Act enacted Jul 2025; affected credits unavailable for vehicles acquired after 30 Sep 2025.|May weaken fleet-electrification economics for logistics suppliers; affects the timing/cost of freight decarbonization.|ev2025
United States|Waste Emissions Charge and rollback [R]|Originally price excess oil/gas methane; later remove the implementing charge rule.|Covered oil/gas facilities meeting reporting and excess-emissions conditions.|Authorized 2022; implementing rule finalized 2024, disapproved and removed in 2025; do not code as continuously operational.|Changes the expected incentive to reduce upstream fuel emissions; distinct from the methane standards above.|wec
Asia|Japan: climate mitigation tax [R]|Price fossil-fuel CO2 emissions; final scheduled rate JPY 289/tCO2.|Fossil-fuel importers/extractors directly; energy users through price pass-through.|Tax began 2012; final planned rate reached Apr 2016.|Changes supplier energy costs and incentives for efficiency/fuel switching; affects embodied input emissions.|japantax
Asia|China: national ETS [R; earlier development initiative]|Improve emissions efficiency through allowance compliance and trading.|Power generators initially; steel, cement and aluminium smelting added in 2025.|Development plan 2017; national trading Jul 2021; sector expansion 2025.|Encourages emissions data and abatement in material suppliers; may affect input prices and sourcing.|china2017,china2025
Asia|Singapore: Carbon Pricing Act / tax [R]|Price emissions: SGD 5/tCO2e initially, SGD 25 in 2024-2025; announced SGD 50-80 ambition by 2030.|Facilities emitting at least 25,000 tCO2e annually; customers indirectly.|Act 2018; tax Jan 2019; increase Jan 2024. The 2030 range was an announced trajectory, not a fixed enacted 2030 rate.|Affects carbon-intensive suppliers' costs and abatement; can inform supplier investment and contract decisions.|sgact,sgtax,sgscope
Asia|China: carbon peak and neutrality commitment [I]|Peak CO2 before 2030; carbon neutrality before 2060.|Government bodies and firms across sectors through subsequent implementation.|Announced Sep 2020; target years 2030 and 2060.|Long-term supplier transition and location signal; not a direct corporate Scope 3 obligation.|chinapledge
Asia|Japan: Green Growth Strategy [I]|Coordinate industrial and technology pathways toward carbon neutrality by 2050.|Priority-sector manufacturers, energy firms, transport and technology developers.|Launched Dec 2020; updated 2021; programmes have separate schedules.|Supports supplier technology roadmaps and procurement of lower-carbon materials/equipment.|japangrowth
Asia|Japan: Green Innovation Fund [I: funding]|Support long-term R&D, demonstration and deployment of decarbonization technologies.|Selected companies and consortia receiving project support.|Established under FY2020 supplementary budget; projects launched from 2021, with multi-year support.|Can support supplier pilots and future low-carbon inputs; funding is not proof of realized reductions.|japanfund
Asia|South Korea: Carbon Neutrality Act [R]|Establish climate governance; 40% national GHG reduction by 2030 versus 2018 under the implementing framework.|Government bodies directly; firms affected through sector policies and support measures.|Enacted 2021; act/decree effective Mar 2022; target year 2030.|Guides supplier transition expectations and engagement in Korean manufacturing supply chains.|korea,koreatarget
Asia|India: Energy Conservation Amendment Act [R]|Enable carbon-credit trading and related energy-transition requirements.|Designated energy-intensive businesses and other entities covered by implementing rules.|Enacted Dec 2022; implementation through later schemes and rules.|Creates the legal basis for supplier carbon-cost and data obligations; no immediate blanket Scope 3 requirement.|indiaccts
Asia|India: Carbon Credit Trading Scheme [R]|Create compliance and offset mechanisms; compliance uses GHG-intensity targets.|Designated obligated industrial entities; eligible voluntary offset project developers.|Notified Jun 2023; amended Dec 2023; implementation and targets phased by sector.|May encourage supplier intensity reductions and measurement; offset certificates do not automatically reduce a buyer's Scope 3 inventory.|indiaccts
Asia|India: National Green Hydrogen Mission [I: incentives]|Support hydrogen production and electrolyser manufacturing; initial INR 19,744 crore outlay.|Selected hydrogen producers, electrolyser manufacturers and participating industrial users.|Approved Jan 2023; support through programme-specific tenders and awards.|May enable lower-carbon fertilizer, steel and chemical inputs; compare lifecycle emissions and delivered cost.|indiah2
Asia|Japan: GX Promotion Act [R]|Finance industrial transition and introduce phased carbon pricing.|Supported industrial projects; large emitters and fossil-fuel suppliers under later mechanisms.|Enacted 2023; ETS full operation scheduled FY2026; fossil-fuel surcharge FY2028.|Changes supplier investment and future carbon-cost expectations; may support long-term low-carbon purchasing contracts.|gxact,gxdates
Asia|Japan: GX League trial ETS [I: voluntary]|Pilot company target-setting and emissions trading before the later mandatory phase.|Voluntarily participating companies.|Trial ETS began Apr 2023; trial phase FY2023-FY2025.|Provides supplier engagement and emissions-performance signals; participation alone does not establish lower product emissions.|gxleague
Asia|Taiwan: carbon fee [R]|Price covered emissions; standard NTD 300/tCO2e, with preferential rates for approved reduction plans.|Covered large manufacturers and electricity generators.|Rates announced Oct 2024; applies to 2025 emissions, first payment scheduled May 2026.|Encourages supplier reduction plans and may alter input prices; useful for material/electronics supplier discussions.|taiwan,twscope'''

DATA += '''
EU member states|Sweden: carbon tax [R: tax]|Price fossil-fuel CO2 emissions to encourage efficiency and fuel switching; coverage includes exemptions and interaction with the EU ETS.|Liable fuel suppliers and taxable fossil-fuel users; transport and heating customers through pass-through.|Introduced 1991; continued through the 2016-2025 review period with changes to rates and exemptions.|May change supplier heat/fuel costs and purchased freight emissions; model the tax only for covered uses.|swedentax
EU member states|France: carbon component of energy excise [R: tax]|Add a CO2-based component to fossil-fuel excise duties; reached EUR 44.60/tCO2 in 2018.|Liable suppliers of taxable petroleum products, natural gas and coal; business fuel users indirectly, subject to exemptions.|Introduced 2014; increased during 2016-2018; distinguish the carbon component from total fuel excise.|Affects fuel-intensive suppliers and logistics costs; can improve economics of efficiency and low-carbon transport.|francetax
EU member states|Ireland: carbon taxes on fuels [R: tax]|Price emissions from liable fuels; Finance Act 2020 legislated a path to EUR 100/tCO2 by May 2030.|Liable fuel suppliers and taxable fuel users; transport, heating and industrial consumers indirectly, with reliefs/exemptions.|Natural gas carbon tax began May 2010; 2020 legislation set annual increases through 2030; implementation dates differ by fuel.|Provides an explicit future carbon-cost path for supplier investment, heating and freight decisions.|irelandtax,irelandstart
EU member states|Netherlands: industrial CO2 levy [R: tax]|Encourage industrial emissions reductions above the exempt amount; eligible ETS participants deduct the specified ETS price from the levy rate.|Covered industrial installations, including relevant non-ETS installations; customers through input costs.|Effective 1 Jan 2021; annual levy and dispensation-right calculations during the review period; not a tax on every emitted tonne.|Changes supplier abatement economics and potential material prices; account for exempt rights and ETS interaction to avoid double-counting costs.|nltax,nltaxets
EU member states|Denmark: industrial green tax reform [R: tax]|Phase in higher industrial CO2 taxation; headline 2030 rates DKK 750/t outside ETS and DKK 375/t for ETS firms, in 2022 prices, with special treatments.|Covered industrial and energy businesses; treatment varies with ETS participation and activity.|Reform agreed 2022; implementing legislation adopted; phase-in 2025-2030.|Can influence supplier location, material prices and abatement investment; do not apply headline rates uniformly across activities.|denmarktax
EU member states|Germany: national fuel ETS [R: trading, not tax]|Price CO2 from covered heating/transport fuels; fixed certificate prices initially, reaching EUR 55/t in 2025.|Businesses placing covered fuels on the market directly; heating and transport users through price pass-through.|Started 1 Jan 2021; fixed-price phase 2021-2025.|Changes freight and supplier heating costs; separate from carbon taxes and EU ETS when coding policy exposure.|germanyprice,germanystart'''

DATA += '''
Netherlands|Climate Act (Klimaatwet) [R: framework law]|Set national climate governance: government pursues 55% lower GHG emissions by 2030 versus 1990 and climate neutrality by 2050 under the 2023 text.|Government directly; firms through implementing sector rules and incentives, not a uniform company reduction quota.|Original act 2019; strengthened text effective 22 Jul 2023; targets 2030 and 2050.|Provides scenarios for Dutch supplier engagement, sourcing and investment; does not directly impose a firm-level Scope 3 target.|nlclimate
Netherlands|SDE++ [I: subsidy programme]|Support large-scale renewable energy and CO2-reducing technologies by addressing the gap between costs and revenues, subject to scheme rules.|Eligible companies and nonprofit organizations developing supported energy or industrial decarbonization projects.|SDE++ application rounds began autumn 2020; subsequent annual rounds; commissioning and support periods are project-specific.|May enable supplier electrification, low-carbon heat and carbon capture; evaluate actual product-level reductions rather than assuming subsidy receipt reduces Scope 3.|nlsde,nlsdescope
Netherlands|Energy Investment Allowance (EIA) [R: tax incentive]|Permit extra deduction of qualifying energy-saving investment costs from taxable profit; 40% deduction in 2025, not a 40% cash subsidy.|Eligible businesses paying Dutch income or corporate tax and investing in new qualifying Energy List assets.|Long-running annual scheme active during 2016-2025; 2025 percentage and Energy List apply to qualifying 2025 investments.|Improves economics of supplier efficiency and eligible equipment; can lower purchased-product emissions through actual supplier energy savings.|nleia
Netherlands|MIA and Vamil [R: tax incentives]|MIA allows additional deduction up to 45% of qualifying investment; Vamil allows flexible depreciation of 75%, according to asset/list conditions.|Eligible Dutch income/corporate taxpayers investing in assets on the applicable Environmental List.|Annual schemes active during 2016-2025; asset eligibility and benefit depend on investment year; figures describe the 2025 scheme.|Can support supplier circularity and cleaner equipment; check lifecycle effects because environmental eligibility is broader than GHG reduction.|nlmia
Netherlands|Energy-saving and reporting obligations [R]|Require applicable energy-saving measures with payback of five years or less, plus reporting or investigation obligations.|Covered business/institutional locations using at least 50,000 kWh electricity or 25,000 m3 natural-gas equivalent annually, subject to scope rules.|Existing duty expanded from Jul 2023; reporting deadline 1 Dec 2023 in that cycle; generally four-year reporting.|Supplier compliance can reduce embodied emissions and reveal investment opportunities; the buyer's own energy savings are principally Scope 1/2.|nlenergy,nlenergydate
Netherlands|Municipal zero-emission zones for urban freight [R: local access rules]|Restrict access by emitting commercial vans and trucks, with transitional arrangements and exemptions.|Carriers, tradespeople, delivery fleets and other van/truck operators entering participating municipal zones.|First zones started Jan 2025; municipal start dates vary; transitional access depends on vehicle class and registration date.|Directly affects carrier selection, last-mile routing and outsourced delivery emissions; a zero-emission tailpipe does not mean zero lifecycle emissions.|nlze,nlze2025
Netherlands|AanZET [I: purchase subsidy]|Support purchase of eligible new zero-emission trucks; funding and support percentages depend on application round and firm size.|Eligible businesses/nonprofits buying qualifying trucks, including eligible leasing companies.|First opened 9 May 2022; subsequent rounds including 2025; procurement and delivery conditions are round-specific.|May lower the cost of contracted zero-emission freight and facilitate buyer-carrier fleet-transition agreements.|nlaanzet,nlaanzetstart
Netherlands|SEBA [I: purchase subsidy, closed]|Support eligible new zero-emission commercial vans; historical programme rather than an open 2025 incentive.|Eligible entrepreneurs and nonprofit organizations purchasing or financially leasing qualifying vans.|Ran 15 Mar 2021 to 31 Dec 2024; closed to new applications in 2025.|Supported cleaner delivery fleets and may affect later outsourced-transport emissions; do not include it as available funding for new 2025 purchases.|nlseba'''

rows = [line.split('|') for line in DATA.splitlines()]
for row in rows:
    if row[1].startswith('Netherlands: industrial CO2 levy'):
        row[0] = 'Netherlands'
assert all(len(r) == 7 for r in rows)
used = list(dict.fromkeys(['ghgp', 'omnibus'] + [k for r in rows for k in r[-1].split(',')]))
assert not set(used) - set(refs)

intro = ('This inventory consolidates the 2016-2025 timeline, additional 2030-target instruments, selected national carbon-pricing measures in EU member states, and a dedicated Dutch regulations and incentives section. '
         'National taxes introduced before 2016 are included where they operated during the review period; this is not an exhaustive inventory of every member state. '
         'Repeated milestones for the same instrument are combined. R = regulation or binding legislation '
         '(including legally established incentives); I = initiative, strategy or voluntary programme. '
         'Affected firms include both directly regulated entities and indirect beneficiaries or supply-chain partners, '
         'as indicated. Firm eligibility is summarized, not reproduced as an exhaustive legal test. '
         'Dates after 2025 describe schedules associated with the reviewed measures, not a full current-law update. '
         'The Scope 3 column contains analytical interpretations of potential decision channels, not claims that each '
         'instrument imposes a Scope 3 obligation or has already delivered reductions.')
notes = ('A supplier\'s operational emissions may enter its customer\'s Scope 3 purchased-goods inventory. '
         'The customer\'s own purchased electricity is generally Scope 2; outsourced transport can enter Scope 3. '
         'Carbon pricing, tax credits or offset purchases alone do not demonstrate a reduction in the buyer\'s inventory. '
         'CSRD/CSDDD scope descriptions follow the historical measures: the December 2025 Omnibus agreement was '
         'provisional, with substantive final adoption occurring after this review period.')

def esc(s):
    return ''.join({'&': r'\&', '%': r'\%', '$': r'\$', '#': r'\#', '_': r'\_', '{': r'\{', '}': r'\}'}.get(c, c) for c in s)

tex = r'''% Standalone landscape table with embedded bibliography. Compile twice with pdflatex.
\documentclass[10pt,a4paper,landscape]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[margin=15mm]{geometry}
\usepackage{lmodern,microtype,array,tabularx,booktabs,xurl}
% Extend tabularx to allow page breaks and repeated table headers.
\usepackage{ltablex}
\keepXColumns
\usepackage[hidelinks]{hyperref}
\newcolumntype{Y}[1]{>{\hsize=#1\hsize\linewidth=\hsize\raggedright\arraybackslash}X}
\setlength{\parindent}{0pt}
\setlength{\parskip}{5pt}
\setlength{\tabcolsep}{4pt}
\renewcommand{\arraystretch}{1.18}
\newcommand{\source}[4]{\bibitem{#1} #2. \emph{#3}. \url{#4}.}
\title{Climate Policy Instruments and Scope 3 Decisions}
\author{TRACE3 --- Work Package 4}
\date{Policy review period 2016--2025}
\begin{document}
\maketitle
'''
tex += esc(intro) + '\n\n' + esc(notes) + r'\cite{ghgp,omnibus}' + '\n'
md = '# Climate policy instruments and Scope 3 decisions\n\n' + intro + '\n\n' + notes + '\n\n'
md += 'Accounting reference: [GHG Protocol](' + refs['ghgp'][2] + '). Historical scope note: [December 2025 agreement](' + refs['omnibus'][2] + ').\n\n'

for region in ['Global', 'European Union', 'EU member states', 'Netherlands', 'United States', 'Asia']:
    tex += '\n\\clearpage\n\\section*{' + esc(region) + '}\n\\small\n'
    tex += r'\begin{tabularx}{\textwidth}{Y{0.85}Y{1.00}Y{0.85}Y{1.05}Y{1.25}}' + '\n'
    header = r'\textbf{Instrument and type} & \textbf{Purpose and target} & \textbf{Affected firms} & \textbf{Implementation dates} & \textbf{Potential Scope 3 connection} \\'
    tex += '\\toprule\n' + header + '\n\\midrule\n\\endfirsthead\n\\toprule\n' + header + '\n\\midrule\n\\endhead\n'
    tex += r'\midrule \multicolumn{5}{r}{Continued on next page} \\ \endfoot \bottomrule \endlastfoot' + '\n'
    md += '**' + region + '**\n\n| Instrument and type | Purpose and target | Affected firms | Implementation dates | Potential Scope 3 connection |\n|---|---|---|---|---|\n'
    for row in (r for r in rows if r[0] == region):
        _, instrument, purpose, firms, dates, connection, keys = row
        cells = [esc(instrument) + r'\cite{' + keys + '}', esc(purpose), esc(firms), esc(dates), esc(connection)]
        tex += ' & '.join(cells) + r' \\' + '\n\\addlinespace[5pt]\n'
        citations = ' '.join('[Source ' + str(i+1) + '](' + refs[k][2] + ')' for i,k in enumerate(keys.split(',')))
        md += '| ' + ' | '.join([instrument + ' ' + citations, purpose, firms, dates, connection]) + ' |\n'
    tex += '\\end{tabularx}\n\\normalsize\n'
    md += '\n'

tex += '\\clearpage\n\\begin{thebibliography}{99}\n\\small\n'
tex += 'References reused from the timeline were accessed on 24 September 2026; supplementary references were checked on 25 September 2026.\n\n'
for key in used:
    author, title, url = refs[key]
    tex += '\\source{' + key + '}{' + esc(author) + '}{' + esc(title) + '}{' + url.replace('%', r'\%') + '}\n'
tex += '\\end{thebibliography}\n\\end{document}\n'
(ROOT / 'climate_policy_scope3_inventory.tex').write_text(tex, encoding='utf-8')
(ROOT / 'climate_policy_scope3_inventory.md').write_text(md, encoding='utf-8')
print(f'Created LaTeX and Markdown inventories: {len(rows)} instruments; {len(used)} bibliography entries.')
